# using np.random

In [26]:
import numpy as np
random_arr = np.random.randint(1,100)
print(random_arr)


22


In [14]:
out_arr =np.random.randint(low = 4, high=10, size=(4,6))
print(out_arr)

[[4 7 6 8 9 5]
 [9 5 7 7 6 4]
 [4 8 6 5 4 4]
 [4 7 6 6 7 7]]


In [23]:
arr1 = np.random.rand(3,3)*9+1
print(arr1)

[[8.36696748 2.24686982 3.07770601]
 [9.66294799 4.09948505 5.49539457]
 [4.55359953 3.6473124  6.88316363]]


In [27]:
arr2=np.random.randint(low=1 ,high =9, size=(5,5))
print(arr2)

[[8 4 3 2 8]
 [8 4 7 4 3]
 [1 3 1 7 6]
 [5 3 2 4 5]
 [6 5 7 1 4]]


In [30]:
arr3 = np.array([1,2,3,4,5,6])
print(arr3[1])
print(arr3)
arr3[1]=9
print(arr3)

2
[1 2 3 4 5 6]
[1 9 3 4 5 6]


# Indexing in one-dimesnional and multi-dimesional arrays

In [31]:
# zero d array                0,1,2,3,4.................
# one d array np.array        [pass zero d array]
# two d array
# three d array
# multi d array

In [ ]:
# making 1d array into 2d array
