# LIBRARY

# Numpy- Numerical Python


In [1]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(type(arr))  #numpy.ndarray where nd is n dimensions

[1 2 3]
<class 'numpy.ndarray'>


# using np.zeros() and np.ones()

In [2]:
zeros_arr = np.zeros((2,3)) #2x3 array of zeros
ones_arr = np.ones((3,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# using np.arrange() and np.linspace()

In [4]:
arange_arr = np.arange(0,10,3)
print(arange_arr)
arange_arr


[0 3 6 9]


array([0, 3, 6, 9])

In [5]:
linspace_arr= np.linspace(0,1,5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
linspace_arr= np.linspace(0,1,2)
linspace_arr

array([0., 1.])

In [7]:
arange_arr = np.arange(0,1,5)
print(arange_arr)
arange_arr

[0]


array([0])

# using np.random

In [16]:
random_arr = np.random.rand(2,3)
random_arr


AttributeError: 'builtin_function_or_method' object has no attribute 'rand'