# Indexing in one-dimesnional and multi-dimesional arrays

In [1]:
# zero d array                0,1,2,3,4.................
# one d array np.array        [pass zero d array]
# two d array
# three d array
# multi d array

# Slicing array and understand views

In [4]:
import numpy as np
arr= np.array([1,2,3,4,5])
sliced_arr = arr[1:4]
print(sliced_arr)

[2 3 4]


In [13]:
import numpy as np
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,0:2]

array([1, 2])

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,0:2])
print(arr)

[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3-D array

In [20]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]]]


In [31]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [30]:
print(arr[0:3,1,0:2])

[[ 4  5]
 [13 14]
 [22 23]]


# copying and viewing datatype


In [54]:
arr = np.array([1,2,3], dtype='int64')
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [45]:
arr = np.array([1,2,3,4])
arr1 = arr.copy()
arr2 = arr.view()
arr[0]=10
print(arr1)
print(arr2)

[1 2 3 4]
[10  2  3  4]


In [47]:
arr2=np.array([4,5,6,7,8,9])
arr3=np.copy(arr2)
#arr4=np.view(arr2)
arr2[2]=1
print(arr3)
#print(arr2)

[4 5 6 7 8 9]
