# Array shape and Reshape

In [32]:
    #shape return the dimensions of an array
    #ndim returns the number of dimensions
    #size returns thetotal number of elements

In [33]:
import numpy as np
arr=np.array([[1,2,3,],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(type(arr))

(2, 3)
2
6
<class 'numpy.ndarray'>


# Reshaping array with reshape()

In [34]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
reshaped_arr = arr.reshape((2,6))
print(arr)
print(arr.shape)
print(reshaped_arr)
print(reshaped_arr.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [35]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_arr = arr.reshape((2,6))
reshaped_arr2 = arr.reshape((2,2,3))
#print(arr)
#print(arr.shape)
#print(reshaped_arr)
#print(reshaped_arr.shape)
print(reshaped_arr2)
print(reshaped_arr2.shape)
reshaped_arr3=reshaped_arr2.reshape(-1)
print(reshaped_arr3)
print(reshaped_arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


# Array Iterating and Universal Functions (ufuncs)

# introduction to nditer

In [44]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

for i in arr:
    print(i)
for elm in np.nditer(arr):
    print(elm)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


# using np.sin() and np.exp()

In [47]:
arr=np.array([1,2,3])
sin_arr = np.sin(arr)
exp_arr = np.exp(arr)
print(sin_arr)
print(exp_arr)

[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]


# array multiplication

In [51]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[5,6,7],[1,1,1]])
result=np.dot(arr1,arr2)
print(result)

[[20 23 26]
 [59 68 77]]
